### ISSUE TITLE
RPC method names should be case insensitive

### ISSUE THREAD

**Issue by hayeah** [bodhiproject/qrypto#125]
Currently they are camel case string constants:

https://github.com/bodhiproject/qrypto/blob/0357177d0c4b779a5104dd74326abfc53d344552/src/constants.ts#L13-L14

The RPC lists the methods as lowercase. It is surprising to require camel case when using qrypto provider.

```
getreceivedbyaddress "address" ( minconf )
importaddress "address" ( "label" rescan p2sh )
listaddressgroupings
listreceivedbyaddress ( minconf include_empty include_watchonly)
listunspent ( minconf maxconf  ["addresses",...] [include_unsafe] [query_options])
sendfrom "fromaccount" "toaddress" amount ( minconf "comment" "comment_to" )
sendmany "fromaccount" {"address":amount,...} ( minconf "comment" ["address",...] replaceable conf_target "estimate_mode")
sendmanywithdupes "fromaccount" {"address":amount,...} ( minconf "comment" ["address",...] )
sendtoaddress "address" amount ( "comment" "comment_to" subtractfeefromamount replaceable conf_target "estimate_mode")
sendtocontract "contractaddress" "data" (amount gaslimit gasprice senderaddress broadcast)
setaccount "address" "account"
```

**Comment by dwalintukan** [comment]
@hayeah This is actually how its set in `WalletRPCProvider` so we had no choice:
![image](https://user-images.githubusercontent.com/4350404/43989911-58a82a20-9d7d-11e8-81c1-ae1da7a9c888.png)

**Comment by hayeah** [comment]
ok.. let me fix that 🤦‍♂️

**Comment by hayeah** [comment]
rpc methods should do case-insensitive match. `qtumjs-wallet 0.1.1`

https://github.com/qtumproject/qtumjs-wallet/blob/master/src/WalletRPCProvider.ts#L23

**Comment by dwalintukan** [comment]
Awesome, thanks @hayeah. Will make the changes.

**Comment by dwalintukan** [comment]
#129
