### ISSUE TITLE
Extension triggers TypeError: _.contains is not a function on some websites

### ISSUE THREAD

**Issue by Clement-Bresson** [bodhiproject/qrypto#149]
Chrome Extension Qrypto version: 1.2.1

When having Qrypto extension installed on Chrome and activated, I got error below on some websites:

![screenshot from 2018-09-05 11-11-16](https://user-images.githubusercontent.com/12169621/45087026-82f2d680-b0fc-11e8-8248-9434cedb912c.png)

It seems to be related to a lodash issue.

To reproduce, here are two websites I encountered this error on:
quay.io
app.clubhouse.io

When disabling the extension, error leaves.

**Comment by dwalintukan** [comment]
@Clement-Bresson thanks for reporting. we will look into this.

**Comment by soshochang** [comment]
@Clement-Bresson thanks for reporting this, found the issue, and it will be fixed in the next release
