### ISSUE TITLE
Mac fullscreen mode, sign tx popup shows in new tab instead of a detached window

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/qrypto#190]
Not sure the possibility of forcing to show in a detached popup window, but should investigate.

![image](https://user-images.githubusercontent.com/4350404/46582443-edd35c80-ca70-11e8-9a3a-f264de339452.png)

**Comment by soshochang** [comment]
@dwalintukan I looked into this a bit, and although there are some other people asking about it (https://productforums.google.com/forum/#!topic/chrome/wnjc4bflKFI) 
I don't see any indication that it is possible to do programmatically on our end.  It seems to be an OS related setting. 
There is some indication that it may be possible at the user level, as a user setting for a particular browser.
Also even if it were possible, I think any new window that is opened would also be opened in full screen mode, which I think is worse then having it open as a new tab.

**Comment by dwalintukan** [comment]
Not a bug then. It's a Mac thing. Skip.
