### ISSUE TITLE
Accept WIP that corresponds to uncompressed public key 

### ISSUE THREAD

**Issue by hayeah** [bodhiproject/qrypto#191]
The length from the WIP string should be either 51 or 52.

https://github.com/bodhiproject/qrypto/blob/433f246f4970071b588eda74b8b2ad1c8dda9a5c/src/utils/index.ts#L52

A public key can be uncompressed or compressed:

https://bitcoin.stackexchange.com/questions/3059/what-is-a-compressed-bitcoin-key

The corresponding private key in WIP format may be 51 (uncompressed) or 52 bytes (compressed), according to:

https://en.bitcoin.it/wiki/Wallet_import_format

The underlying `validatePrivateKey` function should handle either cases.

**Comment by soshochang** [comment]
@hayeah resolved in PR194, will be part of next release
