### ISSUE TITLE
Implement encryption for storing mnemonic in Chrome storage

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/qrypto#24]

**Comment by dwalintukan** [comment]
@scriptfans awesome, will implement this soon! thanks.

**Comment by hayeah** [comment]
@dwalintukan we set the parameters s.t. it takes about 3 seconds to decrypt.

**Comment by dwalintukan** [comment]
@hayeah got it. we will account for the lag with the loading screen.

**Comment by hayeah** [comment]
hmm. also considering unlocked session https://github.com/bodhiproject/qrypto/issues/68, we'll want to store the password (in fact, hash of the password) in memory so until timeout user can use the session without having to re-enter the password.

i thiiiink the password hash in memory could be `bip38.encrypt(userPassword, "qrypto")`, where "qrypto" is a fixed string. This should be enough to avoid rainbow table attack.

**Comment by dwalintukan** [comment]
#70
