### ISSUE TITLE
the whole extension should use a single master password

### ISSUE THREAD

**Issue by hayeah** [bodhiproject/qrypto#67]
+ use the same master password to encrypt different account private keys
+ one lock screen, and when unlocked, user should see a list of available accounts (home)
+ when importing mnemonic or private key, don't need separate passwords

# proposal

To encrypt private keys with user specified password

+ when init chrome extension, generate a salt, store it in storage. This is `extensionSalt`
  + this is a per-install salt. Never changes unless user resets the wallet
  + Use webcyrpto standard to get cryptographic random salt. 16 bytes: `crypto.getRandomValues(new Uint8Array(16));` 
+ `userPassword` hashed expensively (3~5 seconds) to derive `userPasswordHash`
  + `userPasswordHash = scrypt(userPassword, extensionSalt)`. 
  + we may store `userPasswordHash` in memory
+ `privateKey` encrypted cheaply (<100ms) to derive `encryptedPrivateKey`
  + `encryptedPrivateKey = bip38.encrypt(privateKey, userPasswordHash)`
+ we may store `encryptedPrivateKey` in chrome local storage

```
// calculate userPasswordhash
const extensionSalt = getExtensionSalt(); // from extension storage or generate new one
const userPasswordHash = scrypt(userPassword, extensionSalt);

// store `userPasswordHash` for unlocked session if necessary
session.setPasswordHash(userPasswordHash) 
```

To encrypt private key:

```
// userPasswordHash fetched from unlocked session, or
//   display password prompt, to recreate passwordHash

userPasswordHash = session.passwordHash
const encryptedPrivateKey = bip38.encrypt(privateKey, userPasswordHash)
```

To decrypt private key

```
userPasswordHash = session.passwordHash
const privateKey = bip38.decrypt(encryptedPrivateKey, userPasswordHash)
```

**Comment by hayeah** [comment]
Let's discuss this a bit.

My assumption is that if you require different passwords for "extra security", you'd probably be better-off to not keep the account with lots of fund in a cold / hardware wallet instead.

**Comment by dwalintukan** [comment]
we can adjust this. so my suggestion would be for storing the pw locally then per session. i'll add this when i add the wallet seed encryption.

**Comment by dwalintukan** [comment]
#70
