### ISSUE TITLE
implement unlocked sessions, so user does not have to enter password everytime

### ISSUE THREAD

**Issue by hayeah** [bodhiproject/qrypto#68]
+ store session password in memory in background page
+ remove session password after a timeout

should we worry about memory inspection by hostile process? probably not part of security model. Just assume Chrome's internal process isolation, and guard against other chrome processes.

**Comment by soshochang** [comment]
@hayeah @dwalintukan @scriptfans 
What do you guys think of storing the passwordHash in memory in the background page instead or the pw? It would save the user from having to wait for the 3 second loading from hashing the password. But I'm not sure if it is secure - it would no longer rely on the AppSalt for logging into the app.

**Comment by dwalintukan** [comment]
#95
